// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
  getDefaults: () => __TAURI_INVOKE<Defaults>("get_defaults"),
  getGlobals: () => __TAURI_INVOKE<Globals>("get_globals"),
  getConfigs: () => __TAURI_INVOKE<TargetConfig[]>("get_configs"),
  getSkills: () => __TAURI_INVOKE<SkillMetadata[]>("get_skills"),
  getConfig: (configId: string) =>
    __TAURI_INVOKE<TargetConfig>("get_config", { configId }),
  createConfig: (target: TargetConfig) =>
    __TAURI_INVOKE<null>("create_config", { target }),
  updateConfig: (configId: string, target: TargetConfig) =>
    __TAURI_INVOKE<null>("update_config", { configId, target }),
  deleteConfig: (configId: string) =>
    __TAURI_INVOKE<null>("delete_config", { configId }),
  getSkill: (skillId: string) =>
    __TAURI_INVOKE<SkillEditorRecord>("get_skill", { skillId }),
  createSkill: (
    skillId: string,
    body: string,
    metadata: SkillMetadata,
    frontmatterLines: string[],
  ) =>
    __TAURI_INVOKE<null>("create_skill", {
      skillId,
      body,
      metadata,
      frontmatterLines,
    }),
  updateSkill: (
    skillId: string,
    body: string,
    metadata: SkillMetadata,
    frontmatterLines: string[],
  ) =>
    __TAURI_INVOKE<null>("update_skill", {
      skillId,
      body,
      metadata,
      frontmatterLines,
    }),
  deleteSkill: (skillId: string) =>
    __TAURI_INVOKE<null>("delete_skill", { skillId }),
  readInstructions: () => __TAURI_INVOKE<string>("read_instructions"),
  writeInstructions: (content: string) =>
    __TAURI_INVOKE<null>("write_instructions", { content }),
  startGithubLogin: () =>
    __TAURI_INVOKE<GithubLoginStart>("start_github_login"),
  logoutGithub: () => __TAURI_INVOKE<null>("logout_github"),
  getGithubSyncStatus: () =>
    __TAURI_INVOKE<GithubSyncStatus>("get_github_sync_status"),
  setupGithubSync: () => __TAURI_INVOKE<GithubSyncStatus>("setup_github_sync"),
  resolveSyncConflict: (path: string, resolution: SyncConflictResolution) =>
    __TAURI_INVOKE<null>("resolve_sync_conflict", { path, resolution }),
  syncGithubNow: () => __TAURI_INVOKE<SyncResult>("sync_github_now"),
};

/* Types */
export type AppError = {
  code: AppErrorCode;
  message: string;
};

export type AppErrorCode =
  | PathErrorCode
  | ConfigErrorCode
  | SkillErrorCode
  | GithubErrorCode
  | SystemErrorCode;

export type ConfigErrorCode = "config_not_found" | "config_already_exists";

export type Defaults = {
  setupPath: string;
  newTargetConfig: TargetConfig;
};

export type GithubErrorCode =
  | "auth_failed"
  | "keychain_failed"
  | "network"
  | "not_connected"
  | "remote_path_invalid";

export type GithubLoginStart = {
  deviceCode: string;
  userCode: string;
  verificationUri: string;
  expiresIn: number;
  interval: number;
};

export type GithubSyncStatus = {
  connected: boolean;
  repoOwner: string | null;
  repoName: string | null;
  defaultBranch: string | null;
  lastSyncedCommitSha: string | null;
  lastSyncedAt: string | null;
  hasToken: boolean;
  hasLocalChanges: boolean;
};

export type Globals = {
  appName: string;
  setupPath: string;
};

export type PathErrorCode =
  | "invalid_id_length"
  | "invalid_id_format"
  | "path_resolve_root_failed"
  | "path_resolve_path_failed"
  | "path_resolve_parent_failed"
  | "path_escapes_root";

export type SkillEditorRecord = {
  metadata: SkillMetadata;
  body: string;
  frontmatterLines: string[];
};

export type SkillErrorCode =
  | "skill_not_found"
  | "skill_already_exists"
  | "skill_id_mismatch";

export type SkillMetadata = {
  id: string;
  name: string;
  description: string;
  enabled: boolean;
  tags: string[];
};

export type SyncConflict = {
  path: string;
  message: string;
  localContent: string | null;
  remoteContent: string | null;
};

export type SyncConflictResolution = "local" | "remote";

export type SyncResult = {
  status: SyncState;
  conflicts: SyncConflict[];
};

export type SyncState =
  | "not_connected"
  | "up_to_date"
  | "pulled"
  | "pushed"
  | "conflict";

export type SystemErrorCode = "io" | "json" | "emit" | "unknown";

export type TargetConfig = {
  id: string;
  name: string;
  skillsPath: string;
  instructionsPath: string;
  enabled: boolean;
};
